# Generated by Django 6.0.5 on 2026-05-24 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Record Created'), ('approved', 'Record Approved'), ('flagged', 'Record Flagged'), ('rejected', 'Record Rejected'), ('edited', 'Record Edited'), ('locked', 'Record Locked'), ('ingestion_started', 'Ingestion Started'), ('ingestion_completed', 'Ingestion Completed')], max_length=30)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.IntegerField()),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
